// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC94mHK4AoWIA_YMLjhyWD4EjZQCbL6QiI',
    appId: '1:676601215662:web:0ce703a3efccbb9d7a0b3f',
    messagingSenderId: '676601215662',
    projectId: 'b-gymbro-ddb11',
    authDomain: 'b-gymbro-ddb11.firebaseapp.com',
    storageBucket: 'b-gymbro-ddb11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6cpt_pP49HmbVu3gXYhU2BgF2BkFlZxg',
    appId: '1:676601215662:android:ebf4978387d189ca7a0b3f',
    messagingSenderId: '676601215662',
    projectId: 'b-gymbro-ddb11',
    storageBucket: 'b-gymbro-ddb11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_fbyqJv2OGyIWT_GPgDsXf-5g4PqQJk',
    appId: '1:676601215662:ios:281c4322da0c1cb67a0b3f',
    messagingSenderId: '676601215662',
    projectId: 'b-gymbro-ddb11',
    storageBucket: 'b-gymbro-ddb11.appspot.com',
    iosClientId: '676601215662-h5jc6osfpe36tl0rntkrpvjiq3c8bp8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_fbyqJv2OGyIWT_GPgDsXf-5g4PqQJk',
    appId: '1:676601215662:ios:0602a0c486ffbe4c7a0b3f',
    messagingSenderId: '676601215662',
    projectId: 'b-gymbro-ddb11',
    storageBucket: 'b-gymbro-ddb11.appspot.com',
    iosClientId: '676601215662-nq4bfoleerf50ol3sf0m0hvqqm04h89o.apps.googleusercontent.com',
    iosBundleId: 'com.technion.gymbro.gymbro',
  );
}
